### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'includes')

### ISSUE THREAD

**Issue by sebastiancretu** [timjroberts/cucumber-js-tsflow#117]
Hello,

I'm using `"cucumber-tsflow": "4.0.0-rc.7"` and it seems that with this version I started to have issues when the steps are defined with `tags=null` and `timeout=10000`, like below:
```
   @when(
    /lorem (.*) ipsum (.*)/,
    null,
    10000,
  )
```
The error thrown:
```
TypeError: Cannot read properties of null (reading 'includes')
    at normalizeTag (/home/seb/projects/e2e/node_modules/cucumber-tsflow/src/tag-normalization.ts:4:35)
    at /home/seb/projects/e2e/node_modules/cucumber-tsflow/src/step-definition-decorators.ts:70:24
    at DecorateProperty (/home/seb/projects/e2e/node_modules/reflect-metadata/Reflect.js:553:33)
    at Reflect.decorate (/home/seb/projects/e2e/node_modules/reflect-metadata/Reflect.js:123:24)
    at Object.__decorate (/home/seb/projects/e2e/node_modules/tslib/tslib.js:103:96)
    at Object.<anonymous> (/home/seb/projects/e2e/features/op.steps.ts:116:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (/home/seb/projects/e2e/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/seb/projects/e2e/node_modules/ts-node/src/index.ts:1621:12)
```

I didn't had issues on `4.0.0-preview.7`, so this seems to be introduce in this version.

**Comment by Fryuni** [comment]
`null` was never supposed to work there.

Starting from `4-rc.7`, it accepts a `string`, `undefined`, or an object to be used instead of positional parameters (the object is preferred):

```ts
@when('foo', '@tag', 1000)
@when('foo', undefined, 1000)
@when('foo', {timeout: 1000})
```

Even on `4-preview.7`, the signature was `tag?: string`, meaning `string` or `undefined`, but the implementation coincidentaly also worked with `null`.

You probably are using typescript with `strictNullChecks` disabled for it to not outright reject the null there.

**Comment by sebastiancretu** [comment]
Thank you for the detailed explanation. Will close this then
