### ISSUE TITLE
How to handle state shared between scenarios

### ISSUE THREAD

**Issue by Fryuni** [timjroberts/cucumber-js-tsflow#123]
Hi everyone,

Regarding this point:

>  bring it more aligned with cucumber-js, and try to support full feature set of cucumber-js. Notably missing is BeforeAll/AfterAll hooks.

I've updated my local using version 4.0.3 and now I can see/import `beforeAll/afterAll`. However, I'm getting a "binding" error when trying to use context injection and `beforeAll` decorator. If I use `before` decorator, everything works fine.

Here is how I'm using it:

```
@binding([Login, Client])
class HookSteps {
  constructor(protected login: Login, public client: Client) { }
  @beforeAll()
  public async beforeAll(): {
    await this.login.LogIn()
    await this.client.Client(this.login)
    ...
  }
}
```

Here is the error that I'm getting:

```
VError: a BeforeAll hook errored, process exiting: tests\functional\features\support\hooks.ts: Cannot read property 'LogIn' of undefined
   at Runtime.runTestRunHooks (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\runtime\run_test_run_hooks.ts:32:19)
   at processTicksAndRejections (internal/process/task_queues.js:95:5)
   at async Runtime.start (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\runtime\index.ts:103:5)
   at async runCucumber (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
   at async Cli.run (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\cli\index.ts:78:25)
   at async Object.run [as default] (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\cli\run.ts:38:14)
caused by: TypeError: Cannot read property 'LogIn' of undefined
   at Object.BeforeAll (c:\project\code\myapi\test\functional\features\support\hooks.ts:17:22)
   at globalBindFunc (c:\project\code\myapi\node_modules\cucumber-tsflow\src\binding-decorator.ts:256:48)
   at Object.run (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
   at Runtime.runTestRunHooks (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\runtime\run_test_run_hooks.ts:21:50)
   at Runtime.start (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\runtime\index.ts:103:16)
   at runCucumber (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:33)
   at async Cli.run (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\cli\index.ts:78:25)
   at async Object.run [as default] (c:\project\code\myapi\node_modules\@cucumber\cucumber\src\cli\run.ts:38:14)
```

Any thoughts on that?

**Note:** A minor issue from the code, if you check the comments added for these `BeforeAll` and `AfterAll`, they are the same for the `Before` and `After` ones.

Thank you...

_Originally posted by @ericrommel in https://github.com/timjroberts/cucumber-js-tsflow/issues/64#issuecomment-1559601080_

**Comment by Fryuni** [comment]
If the login should be shared between every scenario, you can create a constant in a module:

```ts
// login.ts

class Login {
  // Your login class that you already seem to have
}

// This same constant will be used by every scenario.
export const login = new Login();

// loginSteps.ts
import {beforeAll} from 'cucumber-tsflow';
import {login} from './login';

@binding()
class SharedInitialization {
  @beforeAll
  public static async login(): {
    await login.login();
  }
}

export = Sharedinitialization;
```

As I mentioned on the other issue, this is not recommended because scenarios should be isolated. Using a shared state context like this, a mistake in one scenario might cause another scenario to break, even though it is correct.

**Comment by Fryuni** [comment]
How can I handle this? It's a logging in process and I don't want to log in every scenario. There are more than 2000 scenarios (and growing). A simple login for all of them could be enough

_Originally posted by @ericrommel in https://github.com/timjroberts/cucumber-js-tsflow/issues/64#issuecomment-1564791938_

**Comment by Fryuni** [comment]
> It's a logging in process and I don't want to log in every scenario.

If you mean that you don't want to run the login before each scenario, then do what I sent above.

If you mean that only on some scenarios do you want to login than all the more reason to not use `beforeAll` since that state will apply to _all_ scenarios.
